Host: "localhost"   # 主机地址
Port: 8080          # 监听端口
TextConfig:
  helloText: This is viogami's WebAPI server,you can visit http://viogami.tech to see more details.
p5cc:
  fontSize: 120    # 字体大小
  fontFamily: "p5cc/assets/HarmonyOSSansSC-Bold.TTF"  # 字体
  gutter : 10      # 字体间距
  padding : 240     # 文字边距
  textAlign: center  # 文字对齐方式
  showLogo: true     # 是否显示Logo
  logoScale: 1.0     # Logo缩放比例
  logoOffset: 240     # Logo偏移量
  showWtm: ""     # 水印文字，为空则不显示