Host: "localhost" # 主机地址
Port: 8080 # 监听端口
GinMode: debug # Gin模式
TextConfig:
  helloText: This text will display on the "/" router.

P5cc:
  fontSize: 120 # 字体大小
  fontFamily: "p5cc/assets/HarmonyOSSansSC-Bold.TTF" # 字体
  gutter: 10 # 字体间距
  padding: 240 # 文字边距
  textAlign: center # 文字对齐方式{center,left}
  redProb: 0.33 # 红色字体概率[0,1]
  showLogo: true # 是否显示Logo
  logoScale: 1.0 # Logo缩放比例
  logoOffset: 240 # Logo偏移量
  showWtm: "" # 水印文字，为空则不显示

# Path: wxapi/config/app.yaml
WxApi:
  replyPostURL: "https://bot.gpt4.xxx"
  official_account:
    token: "your-token"
    app_id: "xxx"
    app_secret: "xxx"
  text:
    helloText: "Hello, Welcome "
    simpleReply: "感谢你的关注"
    defaultReply: 这个消息类型开发者还没有进行相应的设置"

AIConfig:
  ChatGPTUrlProxy: "https://api.openai.com/v1/chat/completions"
  DeepSeekUrl: "https://api.deepseek.com/v1/chat/completions"
